config/routes.rb
Rails.application.routes.draw do
  resources :likes, only: %i[create destroy]
  resources :friend_request
  resources :comments
  resources :posts
  resources :bios
  get "/", to: "home#index"
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "home#index"
end

app/models/bio.rb
class Bio < ApplicationRecord
  belongs_to :user
  validates :nickname, presence: true, uniqueness: true
  validates :birth_date, presence: true

  has_one_attached :avatar

  def self.search(search, current_user)
    if search
      requested_users = []
      users_found_by_nickname = Bio.where("lower(nickname) like ?", "%#{search}%")
      users_found_by_name = Bio.where("lower(name) like ?", "%#{search}%")
      users_found_by_surname = Bio.where("lower(surname1) like ?", "%#{search}%")
      result = [users_found_by_nickname, users_found_by_name, users_found_by_surname]
      result.each do |r|
        if r.count > 0 
          r.each do |user|
            if user != current_user.bio
              requested_users << user unless requested_users.include?(user)
            end
          end
        end
      end
      requested_users
    end
  end
end

app/controllers/bios_controller.rb
class BiosController < ApplicationController
  before_action :set_bio, only: %i[ show edit update destroy ]

  # GET /bios/1 or /bios/1.json
  def show
    @posts = current_user.posts.most_recent if current_user.posts
    @find_friend_request = Bio.search(params[:search], current_user)
    @active_friend_requests = FriendRequest.requested?(current_user)
    @pending_to_accept = FriendRequest.pending?(current_user)
    @comment = Comment.new
  end

  # GET /bios/new
  def new
    @bio = Bio.new
  end

  # GET /bios/1/edit
  def edit
  end

  # POST /bios or /bios.json
  def create
    @bio = Bio.new(bio_params)
    @bio.user = current_user
    respond_to do |format|
      if @bio.save
        format.html { redirect_to bio_url(@bio), notice: "Bio was successfully created." }
        format.json { render :show, status: :created, location: @bio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bios/1 or /bios/1.json
  def update
    respond_to do |format|
      if @bio.update(bio_params)
        format.html { redirect_to bio_url(@bio), notice: "Bio was successfully updated." }
        format.json { render :show, status: :ok, location: @bio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bios/1 or /bios/1.json
  def destroy
    @bio.destroy

    respond_to do |format|
      format.html { redirect_to bios_url, notice: "Bio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bio
      @bio = Bio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bio_params
      params.require(:bio).permit(:nickname, :name, :surname1, 
      :surname2, :birth_date, :address, :city, :province, 
      :postal_code, :country, :phone, :user_id, :avatar, :search)
    end

end

app/helpers/bios_helper.rb
module BiosHelper



end

app/views/bios/_bio.html.erb
<div class="container-fluid">
  <div class="row">
      <div class="card">
        <%= image_tag current_user.bio.avatar, 
        alt: 'mi_foto', class: "mx-auto rounded mt-3",
        size:"200x200" %>
        <div class="card-body">
          <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  Personal information
                </button>
              </h2>
              <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  <%= render "bios/personal_info" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/bios/_form.html.erb
<%= form_with(model: bio) do |form| %>
  <% if bio.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bio.errors.count, "error") %> prohibited this bio from being saved:</h2>

      <ul>
        <% bio.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nickname, style: "display: block" %>
    <%= form.text_field :nickname %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :surname1, style: "display: block" %>
    <%= form.text_field :surname1 %>
  </div>

  <div>
    <%= form.label :surname2, style: "display: block" %>
    <%= form.text_field :surname2 %>
  </div>

  <div>
    <%= form.label :birth_date, style: "display: block" %>
    <%= form.date_field :birth_date %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :province, style: "display: block" %>
    <%= form.text_field :province %>
  </div>

  <div>
    <%= form.label :postal_code, style: "display: block" %>
    <%= form.text_field :postal_code %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.file_field :avatar %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bios/_personal_info.erb
<div id="<%= dom_id @bio %>">
<div class="row">
    <p>
    <strong>Nickname:</strong>
    <%= @bio.nickname %>
  </p>
</div>
<div class="row">
  <div class="col-4">
    <p>
      <strong>Name:</strong>
      <%= @bio.name %>
    </p>
  </div>
  <div class="col-4">
    <p>
      <strong>Surname1:</strong>
      <%= @bio.surname1 %>
    </p>  
  </div>
  <div class="col-4">
    <p>
    <strong>Surname2:</strong>
      <%= @bio.surname2 %>
    </p>
  </div>
</div>
<div class="row">
  <div class="col-4">
    <p>
      <strong>Birth date:</strong>
      <%= @bio.birth_date %>
    </p>
  </div>
  <div class="col-4">
    <p>
      <strong>Phone:</strong>
      <%= @bio.phone %>
    </p>
  </div>
</div>
<div class="row">
  <p>
    <strong>Address:</strong>
    <%= @bio.address %>
  </p>
</div>
<div class="row">
  <div class="col-6">
    <p>
      <strong>City:</strong>
      <%= @bio.city %>
    </p>
  </div>
  <div class="col-6">
    <p>
      <strong>Province:</strong>
      <%= @bio.province %>
    </p>
  </div>
</div>
<div class="row">
  <div class="col-6">
    <p>
      <strong>Postal code:</strong>
      <%= @bio.postal_code %>
    </p>
  </div>
  <div class="col-6">
    <p>
      <strong>Country:</strong>
      <%= @bio.country %>
    </p>
  </div>
</div>





  



 










</div>

app/views/bios/edit.html.erb
<h1>Editing bio</h1>

<%= render "form", bio: @bio %>

<br>

<div>
  <%= link_to "Show this bio", @bio %> |
  <%= link_to "Back to bios", bios_path %>
</div>

app/views/bios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bios</h1>

<div id="bios">
  <% @bios.each do |bio| %>
    <%= render bio %>
    <p>
      <%= link_to "Show this bio", bio %>
    </p>
  <% end %>
</div>

<%= link_to "New bio", new_bio_path %>

app/views/bios/new.html.erb
<h1>New bio</h1>

<%= render "form", bio: @bio %>

<br>

<div>
  <%= link_to "Back to bios", bios_path %>
</div>

app/views/bios/show.html.erb
<div class="container-fluid">
  <div class="row mt-3">
    <div class="col-10 col-lg-6 d-flex mx-auto">
      <%= render @bio %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-10 col-lg-6 mb-3 d-flex mx-auto">
      <%= render "friend_request/friendship" %>
    </div>
  </div>
  <div class="row mt-3 d-flex flex-column">
      <% @posts.each do |post| %>
        <%= render partial: "posts/post", locals: {post: post} %>
      <% end %>
    </div>
  </div>
</div>