config/routes.rb
Rails.application.routes.draw do
  resources :likes, only: %i[create destroy]
  resources :friend_request
  resources :comments
  resources :posts
  resources :bios
  get "/", to: "home#index"
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "home#index"
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :user

  def self.reacted?(id1, id2)
    case1 = !FriendRequest.where(user_id: id1, friend_id: id2).empty?
    case2 = !FriendRequest.where(user_id: id2, friend_id: id1).empty?
    case1 || case2
  end

  def self.requested?(id1)
    FriendRequest.where(user_id: id1, confirmed: false)
  end

  def self.pending?(id)
    FriendRequest.where(friend_id: id, confirmed: false)
  end

  def self.confirmed_record?(id1, id2)
    case1 = !FriendRequest.where(user_id: id1, friend_id: id2, confirmed: true).empty?
    case2 = !FriendRequest.where(user_id: id2, friend_id: id1, confirmed: true).empty?
    case1 || case2
  end

  def self.find_friend_request(id1, id2)
    if FriendRequest.where(user_id: id1, friend_id: id2).empty? 
      FriendRequest.where(user_id: id2, friend_id: id1, confirmed: true)[0].id
    else
      FriendRequest.where(user_id: id1, friend_id: id2, confirmed: true)[0].id
    end
  end

end

app/controllers/friend_request_controller.rb
class FriendRequestController < ApplicationController
  def create
    if current_user.send_request(params[:user])
      redirect_to current_user.bio
    end
  end

  def update
    @friend_request = FriendRequest.find(params[:id])
    respond_to do |format|
      if @friend_request.update(confirmed: true)
        format.html { redirect_to bio_url(current_user.bio), notice: "You have a new friend!" }
      end
    end
  end

  def delete
  end

end

app/helpers/friend_request_helper.rb
module FriendRequestHelper
end

app/views/friend_request/_find_friend.html.erb
<div class="accordion-item">
  <h2 class="accordion-header" id="findFriend">
    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFindFriend" aria-expanded="false" aria-controls="collapseOne">
      Invite a friend!
    </button>
  </h2>
  <div id="collapseFindFriend" class="accordion-collapse" aria-labelledby="findFriend" data-bs-parent="#collapseFindFriend">
    <div class="accordion-body">
      <div class="card" style="width:100%">
        <div class="card-body">
          <%= render "home/find_friend" %>
        </div>
        <div class="card-body">
          <ul class="list-group">
            <% if @find_friend_request %>
              <% @find_friend_request.each do |bio| %>
              <div class="row">
                <div class="col-10">
                  <li class="list-group-item"><%= bio.nickname %></li>
                </div>
                <div class="col-2">
                  <%= button_to "Add friend", friend_request_create_path(user: bio.user_id), class:"btn btn-primary rounded"%>
                </div>
              </div>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/friend_request/_friendship.html.erb
<div class="container-fluid mt-3">
  <div class="accordion" id="accordionFriendship">
    <div class="accordion-item">
      <h2 class="accordion-header" id="friendship">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFriendship" aria-expanded="true" aria-controls="collapseOne">
          Friendship
        </button>
      </h2>
      <div id="collapseFriendship" class="accordion-collapse" aria-labelledby="friendship" data-bs-parent="#collapseFriendship">
        <div class="accordion-body"> 
          <div class="accordion" id="accordionFriendshipBody">
            <%= render "friend_request/pending" %>
            <%= render "friend_request/requested" %>
            <%= render "friend_request/find_friend" %>          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/friend_request/_pending.html.erb
<div class="accordion-item">
  <h2 class="accordion-header" id="pendingFriendRequest">
    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapsePending" aria-expanded="false" aria-controls="collapseOne">
      Pending to accept
      <span class="badge bg-primary ms-5"><%= @pending_to_accept.count if @pending_to_accept.count > 0  %></span>
    </button>
       
  </h2>
  <div id="collapsePending" class="accordion-collapse" aria-labelledby="pendingFriendRequest" data-bs-parent="#collapsePending">
    <div class="accordion-body">
      <div class="card" style="width:100%">
        <div class="card-body">
          <ul class="list-group">
            <% if @pending_to_accept %>
              <% @pending_to_accept.each do |user| %>
              <div class="row">
                <div class="col-9">
                  <li class="list-group-item"><%= User.find(user.user_id).bio.nickname %></li>
                </div>
                <div class="col-3">
                  <%= button_to "Accept friend", friend_request_path(user), 
                  method: :patch,
                  class: "btn btn-success rounded"%>
                </div>
              </div>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/friend_request/_requested.html.erb
<div class="accordion-item">
  <h2 class="accordion-header" id="requestedFriedsdhip">
    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFriendsRequested" aria-expanded="false" aria-controls="collapseOne">
      Requested friendship 
      <span class="badge bg-primary ms-5"><%= @active_friend_requests.count %></span>
    </button>
       
  </h2>
  <div id="collapseFriendsRequested" class="accordion-collapse" aria-labelledby="requestedFriedsdhip" data-bs-parent="#collapseFriendsRequested">
    <div class="accordion-body">
      <div class="card" style="width:100%">
        <div class="card-body">
          <ul class="list-group">
            <% if @active_friend_requests %>
              <% @active_friend_requests.each do |user| %>
              <div class="row">
                <div class="col-10">
                  <li class="list-group-item"><%= User.find(user.friend_id).bio.nickname %></li>
                </div>
              </div>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>